# -*- coding: utf-8 -*-
"""Hack_Rare_Data_LoGoFunc_Yeast2Human.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0cg8pAyMFBjHmFUiY3OQR39KPUkcUgz
"""

import pandas as pd

# 1. Read the Excel file
# Adjust the file name/sheet name to match your actual file.
df = pd.read_excel("Hack_Rare_Final.xlsx", sheet_name=0)

# The DataFrame df should have columns like:
#   gene_symbol, predicted_Yeast2Human, predicted_LoGoFunc,
#   Yeast2Human, Vector_Yeast2Human, LoGoFunc, Vector_LoGoFunc

# 2. Create dictionaries to map from gene -> vector
#    One dictionary for Yeast2Human and another for LoGoFunc
map_y2h = dict(zip(df["Yeast2Human"], df["Vector_Yeast2Human"]))
map_logo = dict(zip(df["LoGoFunc"], df["Vector_LoGoFunc"]))

# 3. Use .map() on the 'gene_symbol' column to fill predicted columns
df["predicted_Yeast2Human"] = df["gene_symbol"].map(map_y2h)
df["predicted_LoGoFunc"]    = df["gene_symbol"].map(map_logo)

# 4. Check the updated DataFrame
print(df.head(20))

# 5. (Optional) Save back to Excel/CSV
df.to_excel("Hack_Rare_Final_updated.xlsx", index=False) # Removed the extra space at the beginning of this line
# df.to_csv("Hack_Rare_Final_updated.csv", index=False)